name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build project with Gradle
        run: ./gradlew build

      - name: Upload lib-debug
        uses: actions/upload-artifact@v1
        with:
          name: easy-http-debug.aar
          path: core/build/outputs/aar/core-debug.aar

      - name: Upload lib-release
        uses: actions/upload-artifact@v1
        with:
          name: easy-http-release.aar
          path: core/build/outputs/aar/core-release.aar

      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: lint-results.html
          path: core/build/reports/lint-results.html
