name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project with Gradle
        run: ./gradlew build
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lib
        uses: actions/upload-artifact@v2
        with:
          name: easy-http.aar
          path: core/build/outputs/aar/core-release.aar
